### ISSUE TITLE
Uncatchable NullReferenceException

### ISSUE THREAD

**Issue by LORRIKAN** [dragonfruitnetwork/Link#27]
Hello, I've got an uncatchable NullReferenceException calling "GetStoreListing" method in "SteamStoreAppListingExtensions" class with appid=216938. Is there any way to fix this problem?

**Comment by aspriddell** [comment]
Do you know what app that is? I'm not convinced it even exists:

```
Request to https://store.steampowered.com/app/359550/ -> Tom Clancy's Rainbow Six Siege
Request to https://store.steampowered.com/app/216938/ -> Redirect to https://store.steampowered.com/ (temporary redirect)
```

**Comment by LORRIKAN** [comment]
I'm getting this appid from this api: "https://api.steampowered.com/ISteamApps/GetAppList/v2/?key". It's the first one. I suppose this is some test app, which doesn't have any information about itself. Of course, I could just skip it, but I need to get information about all apps in this list and I'm afraid I won't be able to manage all such "test" apps in it.

**Comment by aspriddell** [comment]
ah that explains it - in that case in your loop you could try putting the method inside a try/catch block.

it might be worth checking for a redirect/whatever response code and in that case return `null`

**Comment by LORRIKAN** [comment]
> ah that explains it - in that case in your loop you could try putting the method inside a try/catch block.
> GetStoreListing - do you mean this method? I already have it in try-catch block, and NullReferenceException is still not being handled by catch block. Also I got acquainted with this method examining it's code and discovered that there's no try-catch block. Maybe this exception occurs here: `var response = client.Perform<JObject>(request);` or here `return response[appId.ToString()]!["data"]!.ToObject<SteamStoreAppListing>();` and it isn't thrown outside, so external code can't handle it?
> it might be worth checking for a redirect/whatever response code and in that case return `null`
Nice solution which I would use, if there will be no better one.

**Comment by aspriddell** [comment]
> I already have it in try-catch block, and NullReferenceException is still not being handled by catch block. 

If that's the case then it should 100% be caught (see my example screenshot)

![image](https://user-images.githubusercontent.com/10289119/99910060-e8364080-2ce3-11eb-9ec4-e164bc2fb90b.png)

regardless i want to lower the framework to .net std 2 so the nulls will be taken care of when that happens

**Comment by LORRIKAN** [comment]
That's weird. However, after changing the code according to request #28 I finally catched that exception. Thank you for your response. Can I close this issue?

**Comment by aspriddell** [comment]
#28 will be merged and will appear in the main release soon
